### ISSUE TITLE
Windows: Not able to load LanguageResource from classpath

### ISSUE THREAD

**Issue by pkluegl** [DFKI-MLT/JTok#1]
LanguageResource line 114/115
Path.toString() produces backslashes on Windows machines, which cannot be used for classpath lookup. As a result only the FileInputStream works in FileTools.openResourceFileAsStream()

**Comment by jsteffen** [comment]
Good find, thx!

**Comment by pkluegl** [comment]
Are there plans for the next release? I could really use this fix :-)

**Comment by jsteffen** [comment]
Here you go ;-)
