### ISSUE TITLE
Use a logging API instead of hard-depending on a logging backend

### ISSUE THREAD

**Issue by reckart** [DFKI-MLT/JTok#10]
JTok 2.1.20 hard-depends on logback-classic. This is problematic when JTok is used as a library in an application as opposed to a command line tool (I don't know if JTok includes a main class). When used as a library in an application, it should be up to the application developer to choose a suitable backend.

The most popular logging API is currently SLF4J. I would recommend using SLF4J 1.7.x for the time being as SLF4J 2.x does not seem to have a sufficient level of adoption in major libraries yet, which would again cause potential problems for application developers.

**Comment by jsteffen** [comment]
You're right, it's fixed now.

**Comment by reckart** [comment]
Thank you for the quick update.

If you leave the scope at "runtime", then the logback-classic dependency will continue to be a transitive dependency of JTok that downstream users will have to manually exclude if they are not using logback-classic as the logging backend.

If logback-classic is needed for testing, the scope should be "test". 

I believe you used "runtime" to make sure the maven:exec plugin can access the dependency when JTok is run from the command line. To solve this, you could declare logback-classic as a plugin dependency of the exec plugin itself as described here: https://www.mojohaus.org/exec-maven-plugin/examples/example-exec-using-plugin-dependencies.html

**Comment by jsteffen** [comment]
I've adapted the dependencies. Please check if this works for you.
