### ISSUE TITLE
Versioning of 2.0.17 defeats Maven dependency resolution

### ISSUE THREAD

**Issue by reckart** [DFKI-MLT/JTok#2]
The versioning of the new 2.0.17 release does actually pre-date the previous 2.16 according to the versioning scheme as Maven understands it (0 < 16). If JTok would now be drawn in as a transitive dependency through multiple dependencies, the older JTok version wins.

This could be fixed by re-releasing 2.0.17 as 2.17. Alternatively, if a switch to a three-segment versioning scheme is desired, a re-release as 2.1.17 would also fix the problem.

**Comment by jsteffen** [comment]
You're right. I didn't thought about that. I'll create a new release 2.1.17
