### ISSUE TITLE
Support for URLs in FileTools.openResourceFileAsStream(String)

### ISSUE THREAD

**Issue by reckart** [DFKI-MLT/JTok#3]
It would be nice if FileTools.openResourceFileAsStream(String) could also check if treating the location as an URL and opening that as a stream works. Since URLs can point into the classpath (e.g. via `jar:` URLs) as well as to files, it could be used as the first check, before checking for the other options.

**Comment by jsteffen** [comment]
I'm not sure I'm getting your point. `openResourceFileAsStream` no longer takes a String as argument but a Path, so the related URL is always a `file:` URL.

**Comment by reckart** [comment]
Ok, after upgrading to 2.0.17, I see that - but that is actually quite weird. As you say, a "Path" should point to the file system, but then you actually mangle the Path and derive a lookup location within the classpath from it which you pass e.g. to ClassLoader.getSystemResourceAsStream(...).

Passing in a URI/URL to openResourceFileAsStream() would imho make more sense. 

But I actually did like the previous signature where you pass in a String and the code would try several ways of treating that string (i.e. various classpath-based resolving strategies + file-based strategy) - and it would be great if that previous strategy would be extended by also trying a URL-based resolving strategy.  Similar approaches to resolve String to different kinds of locations are employed e.g. in Stanford CoreNLP or DKPro Core and are quite flexible for all kinds of situations.

**Comment by jsteffen** [comment]
> Ok, after upgrading to 2.0.17, I see that - but that is actually quite weird. As you say, a "Path" should point to the file system, but then you actually mangle the Path and derive a lookup location within the classpath from it which you pass e.g. to ClassLoader.getSystemResourceAsStream(...).

The use of a URL was merely a quick way to solve issue #1, i.e. making sure that the lookup string for the classpath always uses forward slashes.

If `openResourceFileAsStream` is supposed to be a general purpose tool method, then extending it in a way that resources are loaded via URL is surely a good idea. But in the context of JTok, it is only required to load resources from the file system and the classpath. So I would leave it as it is for now.
