### ISSUE TITLE
Sentence splitting with SCOLON

### ISSUE THREAD

**Issue by pkluegl** [DFKI-MLT/JTok#5]
There is a preferable approach to split sentences using SCOLON, but only if, e.g., the next token is capitalized or some other type?

**Comment by jsteffen** [comment]
You can add `SCOLON` as a possible terminal punctuation by moving it from [here](https://github.com/DFKI-MLT/JTok/blob/master/src/main/resources/jtok/en/en_class_hierarchy.xml#L104) and to [here](https://github.com/DFKI-MLT/JTok/blob/master/src/main/resources/jtok/en/en_class_hierarchy.xml#L43) in the token class hierarchy. Then a sentence end is recognized whenever a `FIRST_UPPER_CASE` token follows.

**Comment by pkluegl** [comment]
Ah Ok, I'll try that. Thank you
