### ISSUE TITLE
JTok Maven Repository no longer available

### ISSUE THREAD

**Issue by reckart** [DFKI-MLT/JTok#9]
Looks like the Maven repository used by JTok is gone:

https://mlt.jfrog.io/artifactory/mlt-mvn-releases-local

Would it be possible to deploy a JTok release that includes https://github.com/DFKI-MLT/JTok/pull/8 to Maven Central?

**Comment by jsteffen** [comment]
Unfortunately, JFrog is no longer available for free, so we moved our Maven artifacts to a repository on GitHub. Please add the following lines to the Maven pom.xml of your project in order to access the latest JTok release and snapshot:
```
  <repositories>
    <repository>
      <id>mlt-github</id>
      <url>https://raw.githubusercontent.com/DFKI-MLT/Maven-Repository/main</url>
    </repository>
  </repositories>
```
